# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/parallels/lei

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/parallels/lei

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/lei/CMakeFiles /home/parallels/lei/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/lei/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lei

# Build rule for target.
lei: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lei
.PHONY : lei

# fast build rule for target.
lei/fast:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/build
.PHONY : lei/fast

examples/echo.o: examples/echo.cpp.o

.PHONY : examples/echo.o

# target to build an object file
examples/echo.cpp.o:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/examples/echo.cpp.o
.PHONY : examples/echo.cpp.o

examples/echo.i: examples/echo.cpp.i

.PHONY : examples/echo.i

# target to preprocess a source file
examples/echo.cpp.i:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/examples/echo.cpp.i
.PHONY : examples/echo.cpp.i

examples/echo.s: examples/echo.cpp.s

.PHONY : examples/echo.s

# target to generate assembly for a file
examples/echo.cpp.s:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/examples/echo.cpp.s
.PHONY : examples/echo.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/socket.o: src/socket.cpp.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cpp.o:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/socket.cpp.o
.PHONY : src/socket.cpp.o

src/socket.i: src/socket.cpp.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cpp.i:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/socket.cpp.i
.PHONY : src/socket.cpp.i

src/socket.s: src/socket.cpp.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cpp.s:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/socket.cpp.s
.PHONY : src/socket.cpp.s

src/thread.o: src/thread.cpp.o

.PHONY : src/thread.o

# target to build an object file
src/thread.cpp.o:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/thread.cpp.o
.PHONY : src/thread.cpp.o

src/thread.i: src/thread.cpp.i

.PHONY : src/thread.i

# target to preprocess a source file
src/thread.cpp.i:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/thread.cpp.i
.PHONY : src/thread.cpp.i

src/thread.s: src/thread.cpp.s

.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.cpp.s:
	$(MAKE) -f CMakeFiles/lei.dir/build.make CMakeFiles/lei.dir/src/thread.cpp.s
.PHONY : src/thread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lei"
	@echo "... examples/echo.o"
	@echo "... examples/echo.i"
	@echo "... examples/echo.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

